apiVersion: v1
kind: Service
metadata:
  name: simple-microservices-service
spec:
  selector:
    app: simple-microservices-deployment
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001 
    nodePort: 30003